import '@/styles/globals.css'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import { Metadata } from 'next/types'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { OpenPanelComponent } from '@openpanel/nextjs'
import { env } from '@/lib/env'

export const metadata: Metadata = {
  title: 'Bckgrnd | Streamline your design workflow',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en' suppressHydrationWarning>
      {process.env.NODE_ENV === 'production' && (
        <OpenPanelComponent
          clientId={env.OPENPANEL_CLIENT_ID}
          clientSecret={env.OPENPANEL_CLIENT_SECRET}
          trackScreenViews={true}
        />
      )}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} font-medium antialiased`}
      >
        <ThemeProvider attribute='class' forcedTheme='dark'>
          <main className='h-screen w-screen'>
            {children}
            <Toaster />
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
