import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import Script from 'next/script'
import { Metadata } from 'next/types'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Bckgrnd | Streamline your design workflow.',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      {process.env.NODE_ENV === 'production' && (
        <Script
          defer
          src='https://analytics.strmrlab.de/script.js'
          data-website-id='7476744a-1a22-40d5-81d1-4bd685f3f0ae'
        />
      )}
      <body className='antialiased'>
        <ThemeProvider attribute={'class'} forcedTheme='light'>
          <NuqsAdapter>
            <main className='w-sreen h-screen'>{children}</main>
          </NuqsAdapter>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
