import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import { Metadata } from 'next/types'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Bckgrnd | Streamline your design workflow.',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body className='antialiased'>
        <ThemeProvider attribute={'class'} forcedTheme='light'>
          <NuqsAdapter>
            <main className='w-sreen h-screen'>{children}</main>
          </NuqsAdapter>
        </ThemeProvider>
        <Toaster />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
